#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rest-client
Version  : 1.8.0
Release  : 6
URL      : https://rubygems.org/downloads/rest-client-1.8.0.gem
Source0  : https://rubygems.org/downloads/rest-client-1.8.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-rest-client-bin
BuildRequires : ruby
BuildRequires : rubygem-addressable
BuildRequires : rubygem-bundler
BuildRequires : rubygem-crack
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-domain_name
BuildRequires : rubygem-http-cookie
BuildRequires : rubygem-mime-types
BuildRequires : rubygem-netrc
BuildRequires : rubygem-pry
BuildRequires : rubygem-pry-doc
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-safe_yaml
BuildRequires : rubygem-spec
BuildRequires : rubygem-unf
BuildRequires : rubygem-unf_ext
BuildRequires : rubygem-webmock

%description
The CA path symlinks can be created by c_rehash(1ssl).
But in order for the tests to work on Windows, they have to be regular files.
You can turn them all into regular files by running this on a GNU system:

%package bin
Summary: bin components for the rubygem-rest-client package.
Group: Binaries

%description bin
bin components for the rubygem-rest-client package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rest-client-1.8.0
gem spec %{SOURCE0} -l --ruby > rubygem-rest-client.gemspec

%build
gem build rubygem-rest-client.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rest-client-1.8.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/rest-client-1.8.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/.rspec
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/AUTHORS
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/bin/restclient
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/history.md
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/rest-client.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/rest_client.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/exceptions.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/payload.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/platform.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/raw_response.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/request.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/resource.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/response.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/windows.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/lib/restclient/windows/root_certs.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/rest-client.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/rest-client.windows.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/integration/capath_digicert/244b5494.0
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/integration/capath_digicert/81b9768f.0
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/integration/capath_digicert/README
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/integration/capath_digicert/digicert.crt
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/integration/capath_verisign/415660c1.0
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/integration/capath_verisign/7651b327.0
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/integration/capath_verisign/README
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/integration/capath_verisign/verisign.crt
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/integration/certs/digicert.crt
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/integration/certs/verisign.crt
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/integration/integration_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/integration/request_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/unit/abstract_response_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/unit/exceptions_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/unit/master_shake.jpg
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/unit/payload_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/unit/raw_response_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/unit/request2_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/unit/request_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/unit/resource_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/unit/response_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/unit/restclient_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/rest-client-1.8.0/spec/unit/windows/root_certs_spec.rb
/usr/lib64/ruby/gems/2.3.0/specifications/rest-client-1.8.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/restclient
