#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rest-client
Version  : 1.8.0
Release  : 5
URL      : https://rubygems.org/downloads/rest-client-1.8.0.gem
Source0  : https://rubygems.org/downloads/rest-client-1.8.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-rest-client-bin
BuildRequires : ruby
BuildRequires : rubygem-addressable
BuildRequires : rubygem-bundler
BuildRequires : rubygem-crack
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-domain_name
BuildRequires : rubygem-http-cookie
BuildRequires : rubygem-mime-types
BuildRequires : rubygem-netrc
BuildRequires : rubygem-pry
BuildRequires : rubygem-pry-doc
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-safe_yaml
BuildRequires : rubygem-spec
BuildRequires : rubygem-unf
BuildRequires : rubygem-unf_ext
BuildRequires : rubygem-webmock

%description
The CA path symlinks can be created by c_rehash(1ssl).
But in order for the tests to work on Windows, they have to be regular files.
You can turn them all into regular files by running this on a GNU system:

%package bin
Summary: bin components for the rubygem-rest-client package.
Group: Binaries

%description bin
bin components for the rubygem-rest-client package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rest-client-1.8.0
gem spec %{SOURCE0} -l --ruby > rubygem-rest-client.gemspec

%build
gem build rubygem-rest-client.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rest-client-1.8.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/rest-client-1.8.0
rspec -I.:lib spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/rest-client-1.8.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/%3c%3c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/AbstractResponse/args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/AbstractResponse/beautify_headers-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/AbstractResponse/cdesc-AbstractResponse.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/AbstractResponse/code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/AbstractResponse/cookie_jar-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/AbstractResponse/cookies-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/AbstractResponse/description-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/AbstractResponse/follow_redirection-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/AbstractResponse/headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/AbstractResponse/net_http_res-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/AbstractResponse/parse_cookie-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/AbstractResponse/raw_headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/AbstractResponse/request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/AbstractResponse/response_set_vars-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/AbstractResponse/return%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/AbstractResponse/to_i-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Exception/cdesc-Exception.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Exception/http_body-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Exception/http_code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Exception/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Exception/message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Exception/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Exception/response-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Exception/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/ExceptionWithResponse/cdesc-ExceptionWithResponse.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Exceptions/cdesc-Exceptions.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/MaxRedirectsReached/cdesc-MaxRedirectsReached.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/MaxRedirectsReached/message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Base/build_stream-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Base/close-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Base/flatten_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Base/flatten_params_array-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Base/headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Base/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Base/length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Base/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Base/read-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Base/short_inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Base/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Base/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Multipart/boundary-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Multipart/build_stream-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Multipart/cdesc-Multipart.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Multipart/close-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Multipart/create_file_field-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Multipart/create_regular_field-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Multipart/handle_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Multipart/headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Multipart/mime_for-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Streamed/build_stream-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Streamed/cdesc-Streamed.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Streamed/length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/Streamed/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/UrlEncoded/build_stream-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/UrlEncoded/cdesc-UrlEncoded.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/UrlEncoded/handle_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/UrlEncoded/headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/cdesc-Payload.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/generate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/has_file%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Payload/has_file_array%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Platform/cdesc-Platform.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Platform/jruby%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Platform/mac_mri%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Platform/windows%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/RawResponse/cdesc-RawResponse.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/RawResponse/file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/RawResponse/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/RawResponse/request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/RawResponse/size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/RawResponse/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Redirect/cdesc-Redirect.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Redirect/message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Redirect/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Redirect/url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/args-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/cdesc-Request.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/cookies-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/decode-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/default_headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/default_ssl_cert_store-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/execute-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/execute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/fetch_body-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/log_request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/log_response-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/make_headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/max_redirects-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/maybe_convert_extension-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/method-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/net_http_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/net_http_do_request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/net_http_request_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/open_timeout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/parse_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/parse_url_with_auth-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/parser-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/password-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/payload-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/print_verify_callback_warnings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/process_payload-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/process_result-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/process_url_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/processed_headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/raw_response-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/setup_credentials-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/ssl_opts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/stringify_headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/timeout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/transmit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/user-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/valid_cookie_key%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/valid_cookie_value%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Request/verify_ssl-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/RequestFailed/cdesc-RequestFailed.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/RequestFailed/message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/RequestFailed/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Resource/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Resource/block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Resource/cdesc-Resource.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Resource/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Resource/get-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Resource/head-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Resource/headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Resource/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Resource/open_timeout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Resource/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Resource/password-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Resource/patch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Resource/post-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Resource/put-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Resource/timeout-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Resource/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Resource/url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Resource/user-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Response/body-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Response/cdesc-Response.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Response/create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/ResponseForException/cdesc-ResponseForException.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/ResponseForException/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/SSLCertificateNotVerified/cdesc-SSLCertificateNotVerified.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/SSLCertificateNotVerified/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/ServerBrokeConnection/cdesc-ServerBrokeConnection.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/ServerBrokeConnection/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Windows/RootCerts/CERT_CONTEXT/cdesc-CERT_CONTEXT.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Windows/RootCerts/cdesc-RootCerts.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Windows/RootCerts/each-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Windows/RootCerts/instance-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Windows/RootCerts/load_certs-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Windows/RootCerts/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/Windows/cdesc-Windows.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/add_before_execution_proc-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/cdesc-RestClient.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/create_log-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/delete-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/get-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/head-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/log%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/patch-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/post-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/proxy-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/put-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/reset_before_execution_procs-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/RestClient/version-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/rest-client-1.8.0/ri/page-history_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/.rspec
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/AUTHORS
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/bin/restclient
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/history.md
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/rest-client.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/rest_client.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/exceptions.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/payload.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/platform.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/raw_response.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/request.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/resource.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/response.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/windows.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/lib/restclient/windows/root_certs.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/rest-client.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/rest-client.windows.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/integration/capath_digicert/244b5494.0
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/integration/capath_digicert/81b9768f.0
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/integration/capath_digicert/README
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/integration/capath_digicert/digicert.crt
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/integration/capath_verisign/415660c1.0
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/integration/capath_verisign/7651b327.0
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/integration/capath_verisign/README
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/integration/capath_verisign/verisign.crt
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/integration/certs/digicert.crt
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/integration/certs/verisign.crt
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/integration/integration_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/integration/request_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/unit/abstract_response_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/unit/exceptions_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/unit/master_shake.jpg
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/unit/payload_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/unit/raw_response_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/unit/request2_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/unit/request_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/unit/resource_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/unit/response_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/unit/restclient_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/rest-client-1.8.0/spec/unit/windows/root_certs_spec.rb
/usr/lib64/ruby/gems/2.2.0/specifications/rest-client-1.8.0.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/restclient
